biller/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path('denial_posting/', include('denial_posting.urls')),

]

denial_posting/urls.py
from django.urls import path

app_name = 'denial_posting'

from . import views
urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('upload/', views.upload, name='upload'),
    path('review/', views.review, name='review'),
]

members/urls.py
from django.urls import path
from . import views

app_name = 'members'


urlpatterns = [
    path('login_user/', views.login_user, name='login_user')
]

myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

denial_posting/models.py
from django.db import models

# Create your models here.

myapp/models.py
from django.db import models

# Create your models here.

class Recipe(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    ingredients = models.TextField()
    instructions = models.TextField()

denial_posting/views.py
from django.shortcuts import render

# Create your views here.
def dashboard(request):
    return render(request, 'dashboard.html')

def upload(request):
    return render(request, 'upload.html')

def review(request):
    return render(request, 'review.html')

members/views.py
from django.shortcuts import render, redirect       
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.urls import reverse


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'You are now logged in')
            return redirect(reverse('denial_posting:dashboard'))
        else:
            messages.success(request, 'Invalid credentials')
            return redirect('login_user')
    else:
        return render(request, 'authenticate/login.html')  
# Create your views here.

myapp/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def contact(request):
    return render(request, 'contact.html')

denial_posting/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Denial Manager
      {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"  rel="stylesheet" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'home' %}">sky</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'denial_posting:upload' %}">Upload</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'denial_posting:review' %}">Review</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block content %} 
      <p>Denial Mangement dashboard</p>
      {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" ></script>
  </body>
</html>

denial_posting/templates/review.html
{%extends 'dashboard.html'%}
{%block content%}

<p>this is review</p>

{%endblock%}

denial_posting/templates/upload.html
{%extends 'dashboard.html'%}

{%block content%}

<p>this is upload</p>

{%endblock%}

members/templates/authenticate/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

{% block content %}

<form action="" method=POST>
  {% csrf_token %}  
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">User Name</label>
      <input type="text" class="form-control" name="username" aria-describedby="emailHelp">
     
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Password</label>
      <input type="password" class="form-control" name="password">
    </div>
    <input type="submit" value = "Submit" class="btn btn-primary"> 
  </form>

{% endblock %}

myapp/templates/Contact.html
{%extends 'base.html'%}
{%block content%}

<div class="mb-3">
  <label for="formGroupExampleInput" class="form-label">Example label</label>
  <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input placeholder">
</div>
<div class="mb-3">
  <label for="formGroupExampleInput2" class="form-label">Another label</label>
  <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Another input placeholder">
</div>

{%endblock%}

myapp/templates/about.html
{%extends 'base.html'%}
{%block content%}

<p>This is the about page</p>

{%endblock%}

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Denial Manager
      {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"  rel="stylesheet" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'home' %}">sky</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'members:login_user' %}">login</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">{% block content %} {% endblock %}</div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" ></script>
  </body>
</html>

myapp/templates/home.html
{%extends 'base.html'%}
{%block content%}


<p>Denial Mangement on steroids</p>

{%endblock%}